# ✅ .gitlab-ci.yml (Maven + Checkstyle + Auto Format on Commit)
image: maven:3.9.5-eclipse-temurin-21

stages:
  - validate
  - test
  - build
  - package

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

checkstyle:
  stage: validate
  script:
    - mvn checkstyle:checkstyle
    - echo "--- Checkstyle Report ---"
    - cat target/checkstyle-result.xml || echo "Checkstyle result not found"
  artifacts:
    paths:
      - target/checkstyle-result.xml
    when: always
  allow_failure: true
  only:
    - merge_requests
    - develop

unit_test:
  stage: test
  script:
    - mvn test
  only:
    - merge_requests
    - develop

build:
  stage: build
  script:
    - mvn clean install -DskipTests
  only:
    - merge_requests
    - develop

package:
  stage: package
  script:
    - mvn package -DskipTests
  only:
    - main
